### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mtrevisan** [dannytheliar/phonologizer#1]
(Sorry for the misuse of this section but I couldn't find a better place to ask you this)
Where have you find the code for the diacritics variable? I mean, I need to find out how to change the features of a segment while adding the raised, lowered, apical, or laminal diacritics to it.
Thank you

**Comment by dannytheliar** [comment]
Not a problem, I'm more surprised anybody's even looked at this than anything!

You can find the diacritics in [scripts/app.js:198](https://github.com/danrouse/phonologizer/blob/b4a212add927476f26a611818f72fdcf579540f2/scripts/app.js#L198), in the `index.diacritics` object. This object is keyed by the unicode diacritic (you _should_ be able to just paste in the unicode symbol, otherwise you can look up the char code in a googleable unicode table), and each item has the feature specifications of that diacritic.

When input strings are parsed, features from diacritics found in `index.diacritics` are applied to their preceding symbols.

The entirety of this application could really use a refactoring and reorganization, but it's been pretty much off my radar for years.

**Comment by mtrevisan** [comment]
Thank you for the response.
What I was looking for is certain diacritics that are missing from the variable, specifically the "raised", "lowered", "apical", and "laminal" ones.
I used your code as a base for mine (that you can find here https://github.com/mtrevisan/library/blob/dev/public_html/app/tools/lang/phonology/Phone.js). I hope this isn't a problem for you.

**Comment by mtrevisan** [comment]
Thank you for the response.
What I was looking for is certain diacritics that are missing from the variable, specifically the "raised", "lowered", "apical", and "laminal" ones.
I used your code as a base for mine (that you can find here https://github.com/mtrevisan/library/blob/dev/public_html/app/tools/lang/phonology/Phone.js). I hope this isn't a problem for you.

**Comment by dannytheliar** [comment]
Certainly not a problem, I'm happy if it helped your coding and linguistics efforts in any way!

I'm not certain I've answered your question though. It appears as though you've successfully added the diacritics you need, but if you have any other questions on this old codebase feel free to ask them here.
